version: "3"

services:
  web:
    build: ./web
    container_name: web
    environment:
      - TERM=xterm-256color
      - DEBIAN_FRONTEND=noninteractive
      - DEBCONF_NONINTERACTIVE_SEEN=true
    ports:
      - 80:80
    depends_on:
      - db
    networks:
      vnet:
        aliases:
          - web
          - app
          - dvwa
          - vuln
          - website
          - webserver
          - vulnerable
          - vulnerability
  db:
    image: mysql
    container_name: db
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=dvwa
      - MYSQL_USER=dvwa
      - MYSQL_PASSWORD=p@ssw0rd
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql
    networks:
      vnet:
        aliases:
          - db
          - database
          - mysql

volumes:
  mysql_data:
  mysql_config:

networks:
  vnet:
