version: "2"

services:

  sftp:
    container_name: sftp
    image: atmoz/sftp
    volumes:
      - ./volume/share:/home/${SFTP_USER}/share
      - ./volume/hostkeys/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key
      - ./volume/hostkeys/ssh_host_dsa_key:/etc/ssh/ssh_host_dsa_key
      - ./volume/hostkeys/ssh_host_ecdsa_key:/etc/ssh/ssh_host_ecdsa_key
      - ./volume/hostkeys/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key
      - ./volume/keyring/sftp/id_rsa.pub:/home/${SFTP_USER}/.ssh/keys/id_rsa.pub:ro
    networks:
      stuxnet:
        aliases:
          - sftp
    ports:
        - 22:22
    command: ${SFTP_USER}:${SFTP_PASS}:1001

  client:
    container_name: client
    build: client
    volumes:
      - ./client/volume/share:/root/share
      - ./client/volume/runner.sh:/root/runner.sh
      - ./client/volume/id_rsa:/root/.ssh/id_rsa
      - ./client/volume/id_rsa.pub:/root/.ssh/id_rsa.pub
    networks:
      stuxnet:
        aliases:
          - client
    depends_on:
      - sftp
    command: /bin/sh /root/runner.sh

networks:
  stuxnet:
